import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from './config.js';

const sb = SUPABASE_URL.startsWith('http') && !SUPABASE_ANON_KEY.startsWith('YOUR_') ? createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
const grid=document.querySelector('#wallGrid'), state=document.querySelector('#wallState'), form=document.querySelector('#postForm'), content=document.querySelector('#content'), counter=document.querySelector('#counter'), category=document.querySelector('#category'), message=document.querySelector('#formMessage'), dialog=document.querySelector('#reportDialog');
let posts=[], filter='all', reportingId=null;
const tokenKey='wall_client_token_v1'; let token=localStorage.getItem(tokenKey); if(!token){token=crypto.randomUUID();localStorage.setItem(tokenKey,token)}
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const ago=d=>{const sec=Math.max(0,(Date.now()-new Date(d).getTime())/1000); if(sec<60)return 'JUST NOW'; if(sec<3600)return `${Math.floor(sec/60)} MIN AGO`; if(sec<86400)return `${Math.floor(sec/3600)} HR AGO`; return `${Math.floor(sec/86400)} DAYS AGO`};
function render(){const shown=filter==='all'?posts:posts.filter(p=>p.category===filter); if(!shown.length){grid.innerHTML='';state.hidden=false;state.innerHTML='<strong>THE WALL IS QUIET.</strong><br>Maybe you should leave something behind.';return} state.hidden=true;grid.innerHTML=shown.map((p,i)=>`<article class="post" style="--i:${i}"><div class="post-meta"><span>${esc(p.category).toUpperCase()}</span><time datetime="${esc(p.created_at)}">${ago(p.created_at)}</time></div><p>${esc(p.content).replace(/\n/g,'<br>')}</p><div class="post-actions"><button class="like" data-id="${p.id}" aria-label="Like this post"><span>${p.liked?'♥':'♡'}</span> ${p.like_count||0}</button><button class="report" data-id="${p.id}">REPORT</button></div></article>`).join('');}
async function load(){if(!sb){state.hidden=false;state.innerHTML='<strong>CONNECT SUPABASE.</strong><br>Add your project URL and anon key in <code>src/config.js</code>.';return} grid.innerHTML='<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>'; const {data,error}=await sb.from('posts').select('id,content,category,like_count,created_at').eq('status','published').order('created_at',{ascending:false}).limit(100); if(error){grid.innerHTML='';state.hidden=false;state.innerHTML='<strong>UNABLE TO LOAD THE WALL.</strong><br><button id="retry" class="text-button">Try again</button>';document.querySelector('#retry')?.addEventListener('click',load);return} posts=data||[];render();}
form.addEventListener('submit',async e=>{e.preventDefault(); message.textContent=''; const text=content.value.trim(); if(!text||!category.value)return; if(!sb){message.textContent='Connect Supabase first.';return} const btn=document.querySelector('#submit');btn.disabled=true;btn.classList.add('loading'); const {data,error}=await sb.rpc('create_post',{p_content:text,p_category:category.value,p_client_token:token});btn.disabled=false;btn.classList.remove('loading');if(error){message.textContent='Unable to publish. Please try again.';return}content.value='';counter.textContent='0 / 500';category.value='';message.textContent='Left anonymously.';await load();document.querySelector('#wall')?.scrollIntoView({behavior:'smooth'});});
content.addEventListener('input',()=>{counter.textContent=`${content.value.length} / 500`;counter.classList.toggle('near',content.value.length>450)});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filters .active').classList.remove('active');b.classList.add('active');filter=b.dataset.filter;render()}));
document.querySelector('#refresh').addEventListener('click',load);
grid.addEventListener('click',async e=>{const like=e.target.closest('.like'), report=e.target.closest('.report');if(like){if(!sb)return;like.disabled=true;const {error}=await sb.rpc('like_post',{p_post_id:like.dataset.id,p_client_token:token});if(!error){const p=posts.find(x=>x.id===like.dataset.id);if(p){p.like_count=(p.like_count||0)+1;p.liked=true;render()}}} if(report){reportingId=report.dataset.id;document.querySelectorAll('input[name=reason]').forEach(x=>x.checked=false);document.querySelector('#reportMessage').textContent='';dialog.showModal()}});
document.querySelector('#reportForm').addEventListener('submit',async e=>{e.preventDefault();const reason=document.querySelector('input[name=reason]:checked')?.value;if(!reason)return;const b=document.querySelector('#reportSubmit');b.disabled=true;if(sb){const {error}=await sb.rpc('report_post',{p_post_id:reportingId,p_reason:reason,p_client_token:token});document.querySelector('#reportMessage').textContent=error?'Unable to report. Please try again.':'Thanks. We\'ll take a look.';if(!error)setTimeout(()=>dialog.close(),900)}b.disabled=false});
const menu=document.querySelector('.menu');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));document.querySelector('.nav nav').classList.toggle('open',!open)});document.querySelectorAll('.nav nav a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');document.querySelector('.nav nav').classList.remove('open')}));
load();
